// <auto-generated />
namespace Biblioteca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CampoEstatusBibliotecaLibro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoEstatusBibliotecaLibro));
        
        string IMigrationMetadata.Id
        {
            get { return "202509240043532_CampoEstatusBibliotecaLibro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
